services:
  guru-app:
    container_name: aplikasi-izin-admin
    image: mashanz/aplikasi-izin-admin
    network_mode: "host"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      POCKETBASE_SECRET_KEY: ${SECRET_KEY}
      POCKETBASE_URL: ${POCKETBASE_URL}
